import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { PageTemplate} from "@/components";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <PageTemplate>
       <h1>Encontre opções em Delivery próximos á você.</h1>

       <h2>Descubra seu novo Delivery favorito. Milhares de opções a um clique.</h2>
     </PageTemplate>
      
    </div>
  )
}

export default Home
